services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:80"
    env_file:
      - ../.env.local
    volumes:
      - ./app:/code/app
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
      ]
